# Generated by Django 3.0.5 on 2020-05-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_posttwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTwo',
        ),
    ]
